spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
      routes:
        - id: bank-service
          uri: lb://bank-service
          predicates:
            - Path=/banks/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/**

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka