pipeline {
    agent any
    environment {
        GIT_CREDENTIALS_ID = 'github-credentials'
    }
    stages {
        stage('Build') {
            agent{
                docker { image 'maven:3.6.3-jdk-11' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }


    }
}
